version: "2"
services:
  app:
    environment:
      - HOST=0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000